### ISSUE TITLE
Uploading images to facebook

### ISSUE THREAD

**Issue by aTylerRice** [liu044100/SocialVideoHelper#1]
Is there a way to upload images to Facebook using this?

**Comment by liu044100** [comment]
Sorry, this class just used for share video.

You can use `SLComposeViewController` to share just one image.

It seems you want to upload multiple images, maybe you have to use Facebook SDK.

Please check this link https://developers.facebook.com/docs/sharing/ios

Maybe something like this.

```
FBSDKSharePhoto *photo1 = [[FBSDKSharePhoto alloc] init];
photo1.image = image1;
photo1.userGenerated = YES;

FBSDKSharePhoto *photo2 = [[FBSDKSharePhoto alloc] init];
photo2.image = image2;
photo2.userGenerated = YES;

FBSDKSharePhoto *photo3 = [[FBSDKSharePhoto alloc] init];
photo3.image = image1;
photo3.userGenerated = YES;

FBSDKSharePhotoContent *content = [[FBSDKSharePhotoContent alloc] init];
content.photos = @[photo1, photo2, photo3];
...
```

Hope it can help you.
