### ISSUE TITLE
facebook review

### ISSUE THREAD

**Issue by thinium** [liu044100/SocialVideoHelper#11]
Hi, thanks so much for the super easy to use framework.

Sorry this is not an issue report. I used your API to upload videos to FB on behalf of the user. It's working well. I've submitted my app to FB in order to get the publish_actions permission. I just got a response from the FB review team saying that I need to have a login button in my app. But it's not really required since I am using the FB login from the Settings app (The ACAccount). 

I wonder how was your FB review experience. Were you able to get an OK permission using your own API? Thanks in advance!

**Comment by liu044100** [comment]
@ukelady Hello, I used this class in [this app](https://itunes.apple.com/app/id789574985)that can share video to Facebook about 2 years ago, it hasn't a login button, and got an OK permission.

I don't know whether facebook changed the review guide, I think you can contact facebook for more detail.
