### ISSUE TITLE
Validation of "media_ids failed in Stage4"

### ISSUE THREAD

**Issue by manishgant** [liu044100/SocialVideoHelper#2]
When I use Social Video Helper to upload video to twitter, I am getting an error in Stage4. 

Specifically, I am getting "validation of media ids failed." 
### Error Message:

Stage4 HTTP Response: 400, {"errors":[{"code":324,"message":"The validation of media ids failed."}]}
### This is the part of the code used:

```
NSDictionary *postParams = @{@"status": statusContent,
                             @"media_ids" :@[mediaID]};

SLRequest *postRequest = [SLRequest requestForServiceType:SLServiceTypeTwitter requestMethod:SLRequestMethodPOST URL:twitterPostURL parameters:postParams];
postRequest.account = account;
[postRequest performRequestWithHandler:^(NSData *responseData, NSHTTPURLResponse *urlResponse, NSError *error) {
    NSLog(@"Stage4 HTTP Response: %li, %@", (long)[urlResponse statusCode], [[NSString alloc] initWithData:responseData encoding:NSUTF8StringEncoding]);
    if (error) {
        NSLog(@"Error stage 4 - %@", error);
    } else {
        if ([urlResponse statusCode] == 200){
            NSLog(@"upload success !");
            DispatchMainThread(^(){completion();});
        }
    }
}];
```

Is the parameter @[media_ID] supplied to media_ids correct?

**Comment by liu044100** [comment]
It seems like "requests without authentication" when I check Twitter Dev Documentation about HTTP Response: 400.

https://dev.twitter.com/overview/api/response-codes

Did you use the correct ACAccount?

**Comment by manishgant** [comment]
Yes. I seem to have isolated the problem. This was because my video did not have the right encoding and aspect ratio. Screw Twitter for sending out wrong error messages.
