### ISSUE TITLE
Twitter video sharing Issue

### ISSUE THREAD

**Issue by asifrajwana** [liu044100/SocialVideoHelper#4]
Hi,
I have integrated this helper class to share video on twitter, and it working fine until video size is less than or equal to 5MB, but if file size exceeds to 5MB but less than 15MB as allowed by twitter, the video being not shared. This is because of twitter has made limitation that if video size is greater than 5MB but less than 15MB, we need to upload video into chunks. 
Can you help me out. Please.. Thanks in advance

**Comment by liu044100** [comment]
@asifrajwana Thanks for report this bug, I will fix it as soon as possible.

**Comment by mtrung** [comment]
@asifrajwana You can check out my project https://github.com/mtrung/TwitterVideoUpload, which has:
- Support chunk upload
- Built-in support for user's credential retrieval

**Comment by liu044100** [comment]
@asifrajwana Now [SocialVideoHelper](https://github.com/liu044100/SocialVideoHelper) support chunks upload, and support add comment with video, hope it can help you.

Maybe You can also use @mtrung 's  [TwitterVideoUpload](https://github.com/mtrung/TwitterVideoUpload)  , choose that you prefer to.

**Comment by asifrajwana** [comment]
I have already fixed that. Btw thanks a lot
