### ISSUE TITLE
How to chunk video that is over 5MB?

### ISSUE THREAD

**Issue by broderick99** [liu044100/SocialVideoHelper#5]
I'm running into an error when my video is greater than 5MB, see https://twittercommunity.com/t/append-call-in-video-upload-api-giving-error/49067.

Is this a new requirement? Any ideas on how your library would need to be adjusted to accommodate for this requirement? Thanks.

**Comment by liu044100** [comment]
@broderick99 I have fixed the code for the video that  is greater than 5MB about 2 months ago.
Are you using the new code?

**Comment by liu044100** [comment]
@broderick99 hey, guys, does it works?
