### ISSUE TITLE
Upload process aborts when pushing App into background

### ISSUE THREAD

**Issue by quiKsilverItaly** [liu044100/SocialVideoHelper#6]
Hello,
so the last time someone worked on this lib is about a year, but I hope I get a reply.
I use SocialVideoHelper and it is really great, but the uploading process aborts when pushing the App into background. I think this is an important issue.

Sadly I am not familiar with Obj-C (I use Swift), so I hope someone can help.

**Comment by liu044100** [comment]
Hi, @quiKsilverItaly.

Maybe you can check this tutorial about `Background Execution: Performing Finite-Length Tasks`.

https://www.raywenderlich.com/143128/background-modes-tutorial-getting-started

**Comment by quiKsilverItaly** [comment]
Thanks, @liu044100 ! This solved the issue.
